/* Source and licensing information for the line(s) below can be found at https://na.panasonic.com/us/modules/contrib/sitewide_alert/js/init.js. */
'use strict';var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}
function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call&&(typeof call==="object"||typeof call==="function")?call:self;}
function _inherits(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+typeof superClass);}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass;}
(function(Drupal,drupalSettings){var SitewideAlert=function(_React$Component){_inherits(SitewideAlert,_React$Component);function SitewideAlert(props){_classCallCheck(this,SitewideAlert);var _this=_possibleConstructorReturn(this,(SitewideAlert.__proto__||Object.getPrototypeOf(SitewideAlert)).call(this,props));_this.state={dismissed:_this.alertWasDismissed(props.dismissalIgnoreBefore),showOnThisPage:_this.shouldShowOnThisPage(props.showOnPages,props.negateShowOnPages)};_this.dismissAlert=_this.dismissAlert.bind(_this);_this.alertWasDismissed=_this.alertWasDismissed.bind(_this);_this.shouldShowOnThisPage=_this.shouldShowOnThisPage.bind(_this);return _this;}
_createClass(SitewideAlert,[{key:'componentDidUpdate',value:function componentDidUpdate(prevProps){if(this.props.dismissalIgnoreBefore!==prevProps.dismissalIgnoreBefore||this.props.showOnPages!==prevProps.showOnPages||this.props.negateShowOnPages!==prevProps.negateShowOnPages){this.setState({dismissed:this.alertWasDismissed(this.props.dismissalIgnoreBefore),showOnThisPage:this.shouldShowOnThisPage(this.props.showOnPages,this.props.negateShowOnPages)});}}},{key:'shouldShowOnThisPage',value:function shouldShowOnThisPage(){var pages=arguments.length>0&&arguments[0]!==undefined?arguments[0]:[];var negate=arguments.length>1&&arguments[1]!==undefined?arguments[1]:true;if(pages.length===0){return true;}
var pagePathMatches=false;var currentPath=window.location.pathname;for(var i=0;i<pages.length;i++){var baseUrl=drupalSettings.path.baseUrl.slice(0,-1);var page=baseUrl+pages[i];if(page.charAt(page.length-1)==='*'){if(currentPath.startsWith(page.substring(0,page.length-1))){pagePathMatches=true;break;}}else if(page===currentPath){pagePathMatches=true;break;}}
return negate?!pagePathMatches:pagePathMatches;}},{key:'alertWasDismissed',value:function alertWasDismissed(ignoreDismissalBefore){if(!('alert-dismissed-'+this.props.uuid in window.localStorage)){return false;}
var dismissedAtTimestamp=Number(window.localStorage.getItem('alert-dismissed-'+this.props.uuid));if(dismissedAtTimestamp<ignoreDismissalBefore){return false;}
return true;}},{key:'dismissAlert',value:function dismissAlert(){window.localStorage.setItem('alert-dismissed-'+this.props.uuid,String(Math.round(new Date().getTime()/ 1000)));this.setState({dismissed:true,showOnThisPage:this.state.showOnThisPage});}},{key:'render',value:function render(){if(this.props.dismissible&&this.state.dismissed){return null;}
if(!this.state.showOnThisPage){return null;}
var alertClasses='sitewide-alert alert';if(this.props.styleClass!==''){alertClasses+=' '+this.props.styleClass;}
return React.createElement('div',{className:alertClasses,role:'alert'},React.createElement('span',{dangerouslySetInnerHTML:{__html:this.props.message}}),this.props.dismissible&&React.createElement('button',{className:'close',onClick:this.dismissAlert,'aria-label':'Close'},React.createElement('span',{'aria-hidden':'true'},'\xD7')));}}]);return SitewideAlert;}(React.Component);var SitewideAlerts=function(_React$Component2){_inherits(SitewideAlerts,_React$Component2);function SitewideAlerts(props){_classCallCheck(this,SitewideAlerts);var _this2=_possibleConstructorReturn(this,(SitewideAlerts.__proto__||Object.getPrototypeOf(SitewideAlerts)).call(this,props));_this2.state={error:null,isLoaded:false,sitewideAlerts:[]};return _this2;}
_createClass(SitewideAlerts,[{key:'componentDidMount',value:function componentDidMount(){var _this3=this;this.getAlerts();if(drupalSettings.sitewideAlert.automaticRefresh===true){this.interval=setInterval(function(){_this3.getAlerts();},drupalSettings.sitewideAlert.refreshInterval<1000?1000:drupalSettings.sitewideAlert.refreshInterval);}}},{key:'componentWillUnmount',value:function componentWillUnmount(){clearInterval(this.interval);}},{key:'getAlerts',value:function getAlerts(){var _this4=this;fetch(window.location.origin+drupalSettings.path.baseUrl+drupalSettings.path.pathPrefix+'sitewide_alert/load').then(function(res){return res.json();}).then(function(result){_this4.setState({isLoaded:true,sitewideAlerts:result.sitewideAlerts});},function(error){_this4.setState({isLoaded:true,error:error});});}},{key:'render',value:function render(){var _state=this.state,error=_state.error,isLoaded=_state.isLoaded,sitewideAlerts=_state.sitewideAlerts;if(error){console.log('Unable to to load alerts.');return React.createElement('div',null);}else if(!isLoaded){return React.createElement('div',null);}else{return React.createElement('div',null,sitewideAlerts.map(function(sitewideAlert){return React.createElement(SitewideAlert,{key:sitewideAlert.uuid,uuid:sitewideAlert.uuid,message:sitewideAlert.message,styleClass:sitewideAlert.styleClass,dismissible:sitewideAlert.dismissible,dismissalIgnoreBefore:sitewideAlert.dismissalIgnoreBefore,showOnPages:sitewideAlert.showOnPages,negateShowOnPages:sitewideAlert.negateShowOnPages});}));}}}]);return SitewideAlerts;}(React.Component);Drupal.behaviors.sitewide_alert_init={attach:function attach(context,settings){ReactDOM.render(React.createElement(SitewideAlerts,null),document.getElementById('sitewide-alert'));}};})(Drupal,drupalSettings);
/* Source and licensing information for the above line(s) can be found at https://na.panasonic.com/us/modules/contrib/sitewide_alert/js/init.js. */;
/* Source and licensing information for the line(s) below can be found at https://na.panasonic.com/us/modules/contrib/webform/js/webform.element.other.js. */
(function($,Drupal){'use strict';function toggleOther(show,$element,effect){var $input=$element.find('input');var hideEffect=(effect===false)?'hide':'slideUp';var showEffect=(effect===false)?'show':'slideDown';if(show){var width=$element.parent().width();if(width){$element.width(width);}
$element[showEffect]();if(effect!==false){$input.trigger('focus');}
$input.prop('required',true).attr('aria-required','true');var value=$input.data('webform-value');if(typeof value!=='undefined'){$input.val(value);var input=$input.get(0);if($.inArray(input.type,['text','search','url','tel','password'])!==-1){input.setSelectionRange(0,0);}}
$element.parent().find('.CodeMirror').each(function(index,$element){$element.CodeMirror.refresh();});}
else{$element[hideEffect]();$input.data('webform-value',$input.val());$input.val('').prop('required',false).removeAttr('aria-required');}}
Drupal.behaviors.webformSelectOther={attach:function(context){$(context).find('.js-webform-select-other').once('webform-select-other').each(function(){var $element=$(this);var $select=$element.find('select');var $input=$element.find('.js-webform-select-other-input');$select.on('change',function(){var isOtherSelected=$select.find('option[value="_other_"]').is(':selected');toggleOther(isOtherSelected,$input);});var isOtherSelected=$select.find('option[value="_other_"]').is(':selected');toggleOther(isOtherSelected,$input,false);});}};Drupal.behaviors.webformCheckboxesOther={attach:function(context){$(context).find('.js-webform-checkboxes-other').once('webform-checkboxes-other').each(function(){var $element=$(this);var $checkbox=$element.find('input[value="_other_"]');var $input=$element.find('.js-webform-checkboxes-other-input');$checkbox.on('change',function(){toggleOther(this.checked,$input);});toggleOther($checkbox.is(':checked'),$input,false);});}};Drupal.behaviors.webformRadiosOther={attach:function(context){$(context).find('.js-webform-radios-other').once('webform-radios-other').each(function(){var $element=$(this);var $radios=$element.find('input[type="radio"]');var $input=$element.find('.js-webform-radios-other-input');$radios.on('change',function(){toggleOther(($radios.filter(':checked').val()==='_other_'),$input);});toggleOther(($radios.filter(':checked').val()==='_other_'),$input,false);});}};Drupal.behaviors.webformButtonsOther={attach:function(context){$(context).find('.js-webform-buttons-other').once('webform-buttons-other').each(function(){var $element=$(this);var $buttons=$element.find('input[type="radio"]');var $input=$element.find('.js-webform-buttons-other-input');var $container=$(this).find('.js-webform-webform-buttons');$container.on('change',function(){toggleOther(($(this).find(':radio:checked').val()==='_other_'),$input);});toggleOther(($buttons.filter(':checked').val()==='_other_'),$input,false);});}};})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://na.panasonic.com/us/modules/contrib/webform/js/webform.element.other.js. */;
/* Source and licensing information for the line(s) below can be found at https://na.panasonic.com/us/modules/contrib/webform/js/webform.element.options.js. */
(function($,Drupal){'use strict';Drupal.behaviors.webformOptionsButtons={attach:function(context){$(context).find('label.webform-options-display-buttons-label > input[type="checkbox"], label.webform-options-display-buttons-label > input[type="radio"]').each(function(){var $input=$(this);var $label=$input.parent();$input.detach().insertBefore($label);});}};})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://na.panasonic.com/us/modules/contrib/webform/js/webform.element.options.js. */;
/* Source and licensing information for the line(s) below can be found at https://na.panasonic.com/us/themes/custom/pna2018/js/components/contact-us-block.js. */
if(!String.prototype.includes){String.prototype.includes=function(search,start){'use strict';if(typeof start!=='number'){start=0;}
if(start+search.length>this.length){return false;}else{return this.indexOf(search,start)!==-1;}};}
(function($,Drupal){'use strict';Drupal.behaviors.contactUsBlock={attach:function(context,settings){var container=$('.contact-panasonic');if(container.length){container.once('contact-tabs-initiated').each(function(){var currentInstance=$(this);Drupal.behaviors.contactUsBlock.contactTabsInit(currentInstance,context,settings);})}},contactTabsInit:function(container,context,settings){var isButtonsStile=container.hasClass('contact-panasonic--style-buttons'),$salesBtn=$('button[aria-controls="tab-panel-1"]',container),$supportBtn=$('button[aria-controls="tab-panel-2"]',container),$salesTab=$('#tab-panel-1',container),$supportTab=$('#tab-panel-2',container),$expandPanel=$('#expand-panel',container),$expandBtn=$('button[aria-controls="expand-panel"]',container),$tabsNavItem=$('.tabs__nav-item',container),url=window.location.href,comparer='/support',$productDiscontinued=settings.pnaProduct!==undefined&&settings.pnaProduct.endOfLifeSupported!==undefined?settings.pnaProduct.endOfLifeSupported:false,$supportApp=$('.category-support-page__support-resources'),$supportDetail=$('.page-node-type-support-detail'),entityTitle=dataLayer!==undefined&&dataLayer.length?dataLayer[0].entityTitle:document.title,entityBundle=dataLayer!==undefined&&dataLayer.length?dataLayer[0].entityBundle:undefined,$phoneLink=$('.contact-panasonic__phone-link'),$chatLink=$('.contact-panasonic__chat-link'),formsStateHidden=$('.contact-panasonic--style-buttons').length?'Had Been':'Had Not Been',$dropdownContainer=$('.contact-panasonic__select-form-container')[0],$dropdown=$('#contact-panasonic-select-id')[0],$submitButton=$('.btn',$dropdownContainer)[0],dropdownForms=$('.contact-panasonic__forms-block')[0],dropdownSalesTab=$('#contact-us-sales-form')[0],dropdownSupportTab=$('#contact-us-support-form')[0];if($dropdownContainer){$($dropdown).change(function(){var selectedOption=$($dropdown).find('option[value="'+$(this).val()+'"]')[0];$(dropdownSupportTab).removeClass('is-current');$(dropdownSalesTab).removeClass('is-current');if($(this).val()===''){$($submitButton).attr('disabled','true');}else{$($submitButton).removeClass('is-hidden');$($submitButton).attr('disabled',null);}
$($dropdown).find('option').map(function(index,option){$(option).attr('selected',null);return option;})
$(selectedOption).attr('selected','selected');})
$($submitButton).on('click',function(){var dropdownValue=$($dropdown).val();if(dropdownValue===''){$(dropdownForms).addClass('is-hidden');}else{dropdownSelectBehavior(dropdownValue);}})}
$('[href="#contact-us-block-anchor"]',context).on('click',function(){$('html, body').animate({scrollTop:$('#contact-us-block-anchor').offset().top-72},300,function(){$('#contact-us-block-anchor')[0].focus();});return false;});if($supportTab.length&&(url.includes(comparer)||$supportApp.length||$supportDetail.length||$productDiscontinued)&&!isButtonsStile){$salesBtn.parent().removeClass('is-active');$salesBtn.attr({'aria-selected':false,'tab-index':-1});$salesTab.removeClass('is-current').attr('aria-hidden','true');$supportBtn.parent().addClass('is-active');$supportBtn.attr({'aria-selected':true,'tab-index':0});$supportTab.addClass('is-current').attr('aria-hidden','false');}
if($salesBtn.length){$salesBtn.on('click',function(event){var section=$(this)[0].innerText;Drupal.behaviors.contactUsBlock.analytic.toggleButtonEngagement+=1;Drupal.behaviors.contactUsBlock.analytic.clickOnTab(section,Drupal.behaviors.contactUsBlock.analytic.toggleButtonEngagement,formsStateHidden);});}
if($supportBtn.length){$supportBtn.on('click',function(event){var section=$(this)[0].innerText;Drupal.behaviors.contactUsBlock.analytic.toggleButtonEngagement+=1;Drupal.behaviors.contactUsBlock.analytic.clickOnTab(section,Drupal.behaviors.contactUsBlock.analytic.toggleButtonEngagement,formsStateHidden);});}
if($expandBtn.length){if(isButtonsStile){$expandBtn.on('click',function(){$expandPanel.toggleClass('is-current');if($expandPanel[0]){$expandPanel[0].toggleAttribute('hidden');}
var exp=$expandBtn.attr('aria-expanded')=='false'?'true':'false';$expandBtn.attr('aria-expanded',exp);});}else{$expandPanel.toggleClass('is-current');if($expandPanel[0]){$expandPanel[0].toggleAttribute('hidden');}}}
function dropdownSelectBehavior(type){$(dropdownForms).removeClass('is-hidden');$($submitButton).addClass('is-hidden');Drupal.behaviors.contactUsBlock.analytic.dropdownEngagementNumber+=1;if(type==='sales'){$(dropdownSalesTab).addClass('is-current');$(dropdownSupportTab).removeClass('is-current');Drupal.behaviors.contactUsBlock.analytic.onDropdownFormSelection('Sales',Drupal.behaviors.contactUsBlock.analytic.dropdownEngagementNumber);}else if(type==='support'){$(dropdownSalesTab).removeClass('is-current');$(dropdownSupportTab).addClass('is-current');Drupal.behaviors.contactUsBlock.analytic.onDropdownFormSelection('Support',Drupal.behaviors.contactUsBlock.analytic.dropdownEngagementNumber);}}
if($phoneLink.length){$phoneLink.each(function(){$(this).on('click',function(){var section=$('.tabs__nav-item.is-active .tabs__nav-btn',container)[0].innerText;Drupal.behaviors.contactUsBlock.analytic.clickOnPhoneNumber(section,entityTitle,entityBundle);});});}
if($chatLink.length){$chatLink.each(function(){$(this).on('click',function(){var section=$('.tabs__nav-item.is-active .tabs__nav-btn',container)[0].innerText;Drupal.behaviors.contactUsBlock.analytic.clickOnChatLink(section,entityTitle);});});}},analytic:{clickOnTab:function(category,increment,formsState){window.dataLayer.push({event:'pnaLeadGenerationFormToggle',eventCategory:'Lead Generation Toggle Button',eventAction:category+' Button Engaged',eventLabel:'Engagement Number: '+increment+' | Lead Forms '+formsState+' Hidden',eventValue:undefined,eventOrigin:'front-end',eventVars:{'toggleButtonType':category,'toggleButtonEngagement':increment,'toggleButtonsFormHidden':'Lead Forms '+formsState+' Hidden',}});},clickOnPhoneNumber:function(category,pageTitle,pageType){window.dataLayer=window.dataLayer||[]
window.dataLayer.push({'event':'pnaLeadGenerationClickCallNumber','eventCategory':category+' Call Number Clicked','eventAction':pageTitle,'eventLabel':pageType,'eventValue':undefined,'formType':category});},clickOnChatLink:function(category,pageTitle){window.dataLayer=window.dataLayer||[]
window.dataLayer.push({'event':'pnaLeadGenerationChatOpeningForm','eventCategory':'Live '+category+' Chat','eventAction':pageTitle,'eventLabel':'Form','eventValue':undefined,'formType':category});},onDropdownFormSelection:function(type,count){window.dataLayer=window.dataLayer||[];window.dataLayer.push({'event':'pnaLeadGenerationFormToggle','eventCategory':'Lead Generation Toggle Button','eventAction':'Contact '+type+' Button Engaged','eventLabel':'Engagement Number: '+count+' | Lead Forms Had Been Hidden','eventValue':undefined,'eventOrigin':'front-end','eventVars':{'toggleButtonType':'Contact '+type,'toggleButtonEngagement':count,'toggleButtonsFormHidden':'Lead Forms Had Been Hidden',}});},toggleButtonEngagement:0,dropdownEngagementNumber:0}};}(window.jQuery,window.Drupal));
/* Source and licensing information for the above line(s) can be found at https://na.panasonic.com/us/themes/custom/pna2018/js/components/contact-us-block.js. */;
/* Source and licensing information for the line(s) below can be found at https://na.panasonic.com/us/themes/custom/pna2018/js/components/a11y-tabs-component.js. */
(function(window,document,$,Drupal){'use strict';Drupal.behaviors.a11yTabs={attach:function(context,settings){if($('.tabs--a11y').length){$('.tabs--a11y').each(function(){Drupal.behaviors.a11yTabs.init($(this));});}},init:function(element){var keys={ARROWS:[37,38,39,40],ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_DOWN:40,ENTER:13,SPACE:32,PAGE_UP:33,PAGE_DOWN:34};var $allTabGroups=element;function findAdjacentTab(startTab,$list,key){var dir=(key===keys.ARROW_LEFT||key===keys.ARROW_UP)?'prev':'next';var adjacentTab=(dir==='prev')?$(startTab.parentNode).prev()[0]:$(startTab.parentNode).next()[0];if(!adjacentTab){var allTabs=$list.find('.tabs__nav-item');if(dir==='prev'){adjacentTab=allTabs[allTabs.length-1];}
else{adjacentTab=allTabs[0];}}
return $(adjacentTab).find('.tabs__nav-btn')[0];}
function setActiveAndInactive(newActive,$list){$list.find('.tabs__nav-item').each(function(){var assocPanelID=$(this).find('.tabs__nav-btn').first().attr('aria-controls');var anchor=$(this).find('.tabs__nav-btn')[0];if(this!==newActive.parentNode){$(this).removeClass('is-active');anchor.tabIndex=-1;anchor.setAttribute('aria-selected','false');$('#'+assocPanelID).removeClass('is-current').attr('aria-hidden','true');}
else{$(this).addClass('is-active');anchor.tabIndex=0;anchor.setAttribute('aria-selected','true');$('#'+assocPanelID).addClass('is-current').removeAttr('aria-hidden');}});}
$allTabGroups.each(function(){var $tabs=$(this);var $navlist=$tabs.find('.tabs__nav');$navlist.on('keydown','.tabs__nav-item .tabs__nav-btn',function(keyVent){var which=keyVent.which;var target=keyVent.target;if($.inArray(which,keys.ARROWS)>-1){var adjacentTab=findAdjacentTab(target,$navlist,which);if(adjacentTab){keyVent.preventDefault();adjacentTab.focus();setActiveAndInactive(adjacentTab,$navlist);}}
else if(which===keys.ENTER||which===keys.SPACE){keyVent.preventDefault();target.click();}
else if(which===keys.PAGE_DOWN){keyVent.preventDefault();var assocPanel=$('#'+this.getAttribute('aria-controls'));if(assocPanel){assocPanel.focus();}}});$navlist.on('click','.tabs__nav-item .tabs__nav-btn',function(){var currentTarget=$navlist.find('.tabs__nav-item.is-active .tabs__nav-btn')[0];if(currentTarget!==$(this)[0]){var eventData={'previousTarget':currentTarget,'newTarget':$(this)[0]};var event=new CustomEvent('rb.tabs.tabChanged',{detail:eventData});$(this)[0].dispatchEvent(event);}
setActiveAndInactive(this,$navlist);});});$(document.body).on('keydown','.tabs__panel',function(e){if(e.which===keys.PAGE_UP){e.preventDefault();var $navlist=$(this).closest('.tabs--a11y').find('.tabs__nav');var activeTab=$navlist.find('.tabs__nav-item.is-active .tabs__nav-btn')[0];if(activeTab){activeTab.focus();}}});}};}(window,window.document,window.jQuery,window.Drupal));
/* Source and licensing information for the above line(s) can be found at https://na.panasonic.com/us/themes/custom/pna2018/js/components/a11y-tabs-component.js. */;
